server:
  port: 8002

spring:
  application:
    name: eureka


security:
  basic:
    enabled: true
  user:
    name: own
    password: 123456

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000


